name: Build release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag for Releases page (ncipollo/release-action)'
        required: true
        type: string
        default: "master"
      commit:
        required: false
        type: string
        default: "GitHub Action debugging, manually triggered"
        description: 'Commit description for Releases page (ncipollo/release-action)'
  push:
    tags: 
      - 'Release_[1-9]+.[0-9]+.[0-9]+.[0-9]+'
jobs:
  build:
    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest

    env:
      Solution_Name: src\TurtleMine.sln
      
    steps:
    - name: Get tag name
      id: tagname
      uses: olegtarasov/get-tag@v2.1.2
      with:
          tagRegex: "(?<package>.*)_(?<version>.*)" 
      
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Retrieve SNK
      continue-on-error: true
      uses: timheuer/base64-to-file@v1.2
      with:
        fileName: 'turtlemine.snk'
        fileDir: './src'
        encodedString: ${{ secrets.TURTLEMINE_SNK }}

    - name: Setup NuGet.exe for use with actions
      uses: NuGet/setup-nuget@v1.1.1
      
    - name: restore packages
      run: nuget restore $env:Solution_Name

    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1.3
     
    - name: Build
      run: msbuild $env:Solution_Name /t:Clean,Rebuild /p:Configuration=$env:Configuration /verbosity:diag
      env:
        Configuration: ${{ matrix.configuration }}
        
    - name: Log built binaries
      run: |
        dir src/bin/Release/*.*

    - name: Upload MSI
      uses: actions/upload-artifact@v3
      with:
        name: Binaries
        path: src/bin/Release/TurtleMine_*bit.msi
        
    - name: Upload dll
      uses: actions/upload-artifact@v3
      with:
        name: MSI Packages
        path: src/bin/Release/TurtleMine*.dll

    - name: Upload dll
      uses: actions/upload-artifact@v3
      with:
        name: executeable
        path: src/bin/Release/TurtleMine*.exe

    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        name: ${{ steps.tagName.outputs.version }}
        bodyFile: changelog.md
        artifacts: "src/bin/Release/TurtleMine_*bit.msi"
        token: ${{ secrets.GITHUB_TOKEN }}
